In [ ]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import imutils
import easyocr
img = cv2.imread('download.jpeg')
print(img)

[[[ 67 110  99]
  [ 68 114 102]
  [ 93 139 127]
  ...
  [246 248 236]
  [247 249 237]
  [245 249 237]]

 [[103 146 131]
  [ 86 131 115]
  [124 171 155]
  ...
  [248 248 236]
  [246 248 236]
  [244 248 236]]

 [[ 85 129 106]
  [ 81 125 102]
  [104 151 129]
  ...
  [249 247 236]
  [247 246 236]
  [245 246 236]]

 ...

 [[177 178 174]
  [178 179 175]
  [177 178 174]
  ...
  [181 182 178]
  [179 180 176]
  [179 180 176]]

 [[179 180 176]
  [179 180 176]
  [178 179 175]
  ...
  [180 181 177]
  [178 179 175]
  [178 179 175]]

 [[179 180 176]
  [179 180 176]
  [179 180 176]
  ...
  [179 180 176]
  [179 180 176]
  [179 180 176]]]


In [ ]:
cascade = cv2.CascadeClassifier('haarcascade_russian_plate_number.xml')

In [ ]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plates = cascade.detectMultiScale(gray, 1.1, 4)
for (x,y,w,h) in plates:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    plate = img[y:y+h, x:x+w]
    cv2.imwrite('number_plate.jpg', plate)

# Display the image
#cv2.imshow('img',img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()
number_plate=cv2.imread('number_plate.jpg')

()


In [ ]:
gray = cv2.cvtColor(number_plate,cv2.COLOR_BGR2GRAY)

error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


In [ ]:
plt.imshow(gray)

In [ ]:
plt.imshow(cv2.cvtColor(gray, cv2.COLOR_BGR2RGB))

In [ ]:
bfilter = cv2.bilateralFilter(gray, 11, 11, 17)

In [ ]:
edged = cv2.Canny(bfilter, 30, 200)

In [ ]:
plt.imshow(cv2.cvtColor(edged, cv2.COLOR_BGR2RGB))

In [ ]:
#  cv.CHAIN_APPROX_NONE gives (734 points) and  with cv.CHAIN_APPROX_SIMPLE (only 4 points)

keypoints = cv2.findContours(edged.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

In [ ]:
# Simplifies how contonours are actually returned
contours = imutils.grab_contours(keypoints)

In [ ]:
contours = sorted(contours, key = cv2.contourArea, reverse = True)[:10]

In [ ]:
print(contours)

In [ ]:
location = None

for contour in contours:
  # cv2.approxPolyDP returns a resampled contour, so this will still return a set of (x, y) points
  approx = cv2.approxPolyDP(contour, 10, True)
  if len(approx) == 4:
    location = approx
    break

In [ ]:
print(location)

In [ ]:
mask = np.zeros(gray.shape, np.uint8)

In [ ]:
new_image = cv2.drawContours(mask, [location], 0, 255, -1)

#new_image = cv2.bitwise_and(img, img, mask = mask)


plt.imshow(cv2.cvtColor(new_image, cv2.COLOR_BGR2RGB))

In [ ]:
(x, y) = np.where(mask == 255)

(x1, y1) = (np.min(x), np.min(y))

(x2, y2) = (np.max(x), np.max(y))

In [ ]:
cropped_image = gray[x1:x2+3, y1:y2+3]

plt.imshow(cv2.cvtColor(cropped_image, cv2.COLOR_BGR2RGB))

In [ ]:
reader = easyocr.Reader(['en'])

result = reader.readtext(gray)

print(result)

In [ ]:
print(result[0][0])

In [ ]:
print(result[0][1])

In [ ]:
text = result[0][1]

font = cv2.FONT_HERSHEY_SIMPLEX

In [ ]:
res = cv2.putText(img, text = text, org = (approx[0][0][0], approx[1][0][1]+60), fontFace = font, fontScale = 1, color = (0, 255, 0), thickness = 5)

In [ ]:
res = cv2.rectangle(img, tuple(approx[0][0]), tuple(approx[2][0]), (0,255, 0), 3)

plt.imshow(cv2.cvtColor(res, cv2.COLOR_BGR2RGB))